---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pihole-configmap.yaml
  - pihole-deployment.yaml
  - pihole-service-dns.yaml
  - pihole-service-web.yaml
  - httproute-pihole.yaml
  # Uncomment after sealing:
  # - pihole-secret.sealed.yaml
