---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    password: AgBiEHq26REBJTBRM6HgyEQeHO1WBtHtusiEk6U3p8wvUuBmALh52WffE9qYkP/mHe1/wo+l0XyvIdmbGPsISc2ivOfFo05q2BaiOS6I+Jc2Ruxffc+dGegNoFmSZhX8L1Hsa06+FE0yQA6MY+7GA66PmxLANFY1h+flkv/22J0Bt5FWU1MeYbnJW8N2J6iMcZH5mvCCO9Z3rS84vSw+AoujFiJZ+KqB2V/A/CppxenJcyyaX4Wi8Zf6G/YztNXRpL2HyQYWpIiBKgK1WN3mgimcW+3jsi8XWkT/mdVB/1VnOHI0h3kqp7hwp/nYiwcZe18jtTz30/XbghACHfDhY/Z1C4JB4n85L8nBFBuBiexNccX38ZDIOYq5OGb8Vnr9eslurhjxAbGIss11P76PvbgmbSvor52OB2z7YV6HC4p16EM7ZMMHyiJfdIaYlI85xG0ReSFagD5PDZmGIhfMZgIB2QP1WTpipc14sZ8hOjDlUpd3Nvy6jWWRIpm6ZIeOY6x+1GAEaSJnaTTdhycb2YcL0gcf9ofe7JtBkl7IBntPBAG/qhm0ejiwExWJ0E+RD+o3ke6T1wEVpewAHOrQ4+fIizjnttJeKLgq45f67rLUc8l0Czb5VPiyVrQu3xpVNYVam9XyduEkS630bkYDvt9YZVaDX/rFVWKUxY2Sn7jIjpnBxZT5KMF9n7yzdxpRnK6qpk0sfg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: pihole
        app.kubernetes.io/managed-by: Helm
        chart: pihole-2.35.0
        heritage: Helm
        release: pihole
      name: pihole-secret
      namespace: pihole
    type: Opaque
