---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgC+YZzRUhnyOulIi3gRJwG/vhVxHGJhfqyf25Nh0ERs7ZoZaKq2+Fg/CxApBziYfonIWwh9wyHRECL4t4eKceXdYDPZg+MXBRAuuh+B3pHPq6ksElJ0+SA3d9QIRTBi7gveMzFPU9Ov9xwr39cwBf3fTkcnqn2maYQ1Jf7itdGaQqAD7jHY5Z/GsX0df0a4WhIs4t5xvbhensBtuUtdzD3CbXDezYgHAE91BqJSCT3nOrYOIdw/j9LN/CVCeV42HpRdgbIaJbJjo+QCAfl2I4Dk1uDc9aXq6VIdqanDyY23Oy3jnbw8EL5A0CkL2QDLGrNdHAIhYGjRxd684OVwMGqvIiDXHq7Ln+nLSv2x8BwmPW79b+9dJEDwxAXAof5vzHDkIyozq7DHb9o/5cfxUmSrpLYAPmlT/5OqOXF2N0bhly2ZfOQW11XSq7LEZ7OqS1lnvLtSYLjjsKoAyFC991LFOBUFkOJXXY6cVdddi1cGInYRDPNzu9WxrzSHTByjxDuG2oV6hzReG10NW207FPaI6NVPElDHXvW3iu+xVwB8cpiYJAuvpNd8tuJWTazO0wF4VgBO2QqlxSy50jLgK3U+x2g9pk/amRUdGHe742jtx7ojnUA1nVyKx0/z6Knmc1obwvIahv5UHJc/+dFiezVJxvl/DMKpjUx2EBFXmXzd4TryRNsqjlv6Cs4rjRsBYaxSA68SP2MMCu2Z2AzbS6sC9x7j7pvR5etzhQRREKx/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: pihole-secret
      namespace: pihole
