---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgCsoG3VsywcK57Md5hvCGaoH3+pBhedNUa4JALsCrkWneghmDoIAUYw4RnUPQWeSvlY5bKq0U7Nus2XIRsiGhLNsQfDOES0Jw+je71htcYAkTqKMT7f8pB4+VS4NmzV0OATobJ06rghtdZAtqmpoUDjq07ilPP3rOJI9VL8nXwRkc2t+JY8dUN1qAhdkjJMypTbAAwcagXs4ZL78UTdBJQsHGYT7113qx2Ob8wKn1ciUpPEjIU9lA2KFiATLkjQqhs+kNND40dqszUYhNWROgG1IboiYiZ7cWW6jDmk/6Vzqth3M/KuYIfrPMDfjcT4qF344gz9sghJfW5ULaCxYuT9XQLfhcYPMev9Z2h9MbvFA5ANA9CyLadXvKwdpBRYtJrwEZ40MM0HIjp+/cbPHzg4DvAruxe1K73i45yDNQfUA6KP5y9qeJ2HPZZkfNgmWlkWpLMTL7JA2Xh6y3Yv2loYEXODVFSMQOnE6PG7XpcqCaNgNdRvsmQ/o7MNC3VUoM6xFyuOKEcOrW35WnaVXuaWFyiXUYHZklzKfPMGjTE10AkpmfOBFHxZHpAmDseXaYU7gkGyjdgM+5cZrFVqAejRR/tsBGhuZjbXR4U2vhJxd7b242THW0iVRvbQNfKj3If5wjETyJYnZzW8GBN6IYtx0brAdLA7gJidy+3ebXYto1DTSqO2bPDCD2SPkUcVsZgMM99WKA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: pihole-secret
      namespace: pihole
