---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAdy4b6jxX9dd68qE48YEjlmCPD49y2icvlUskUxH/ajlwfoXWWOgrzRTfdbvMY9U2TjvTWj6hia2a8+0lfBTXLgUkgrj0fubvF/WEJZ36qMLl2gAkUxu3AKxhRtf6Eufq1Fsyi1PHyETbrZ0mUlLe076tOMMev0n8tDGMcKJWtKaN91e/5Yt/kqxrGHGyknvAdnNOrlvftnneSnnCuIGuDtK2noqYyvRps4TSTgIr8RAqiWATg7pr/hQxajHUVKs6nN1ZkYBk/+IEpb+4ujpZM1gx8PM/f3E+JjveZwWzwfrFhOV+Zncm6SbeIocdJiGogDbV+KMUt08eXJ2425WEp6PAeMOu6wcm27E7RVcP1qmIJHQtB8MedJyK4DIuHI9u3KTj6YtDH5F2WczYrJHjaDjyA4e8rDnfw7AKMGPuTFE0buy07QcX8RsoRPnI6ZywxaIWSgjAwzW7F9+aVuW9vGIL0coj25AI1oY83Q1E8pfiYkLAZ8bN/6OIJxk01R9MO4TD4U1GOI/IYnEH0Z1kxMFmfmebIRH872VqKHKCf48IhkiYAkpgsgcqMfipOJXHSql9KmlSKw9uRlLn/FHtmqFU6G+yM0SQUMf12rdqWwH2aiwOWN096v8ZfJKO58KSJO0X+wYH/KrtaI55AFvNnnTGPacqZ1YT01W1HWJD24WVvTWORu3A5ZQ8EmdiMoAy1CFCxaodQtaeJz6Q3OEFdVIYa4A==
    AWS_SECRET_ACCESS_KEY: AgAVU/Y3kkK9QrpdXsq+vqNVzgMCa51fUp1z8Trtxl2tNFfqXPFg2CbIQblbYIAKYkdzUPivf/EEnCbvXSBW4U54ncNXYkK0cOiL+FQtt87XN5l20s6eqCYysNzkj6wvIJuTbH+f1AwUpajcihpK1MghifOgd8UVwPESYt62vmsv54sRxUgzWxAKtkkU8jYGjr7umoDUAOS9emzA6UVsDli4DLiNDxeIpG1tP5DV8UCEOL6ACqmWpBXCbLKSRWKVxc2B+9nYtz9pi/Ge2Y+RoY/GcDmiUQyk9Xw8LMXDcgaKDP77gSbQCIHEE1gKU39U8WBqVyWTqWFYJwdqttK/kUTUw7/HWVCRu3f9tpxnj7kWCUtjhwiz+dIVVhl3iC5Be3zvbDQhRdhpeUiSF7Os3D9nlyiE15oJXcl9Ib9Els0GEM917ddUBSlrgD798woQpwvictstM3KXa7GAhjKlO9JeRftYtsjySzUyhQWPFWbtHk5Quo/1eEfAA28whEOB18jNZ9m2uobt6fTBvRv5zHjSxZ67SPbZx3lUd2ryI7RETICJrXozZl/pZHUFFeCBGPU9yDI8GpKFRZSiK8WVCz6aLZ55RbcPUSm2OCj4SabWXzU8rbdVqGJhsLNcmxWNkNr622pBgVE0TFfpkj7aXGVEGUF6WqdcjkeI/c/ur3mA+z/rx7taxI6n25zcevxAB/Lg/nG/EjlMfPn8qoLICqlA8BUfHAcyDlz1bDSfe1Ujo4pYtOoXKsAt
  template:
    metadata:
      name: longhorn-backup-secret
      namespace: longhorn-system
