apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin
  template:
    metadata:
      labels:
        name: nvidia-device-plugin
    spec:
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/hostname: fedora # TODO: Update with your GPU node hostname
      priorityClassName: system-node-critical
      tolerations:
        - key: gpu
          operator: Equal
          value: nvidia
          effect: NoSchedule
      containers:
        - name: nvidia-device-plugin
          image: nvcr.io/nvidia/k8s-device-plugin:v0.14.5
          args:
            - --pass-device-specs=true
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: nvidia-libs
              mountPath: /usr/local/nvidia/lib64
              readOnly: true
            - name: dev
              mountPath: /dev
            - name: sys
              mountPath: /sys
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: nvidia-libs
          hostPath:
            path: /opt/nvidia-libs # TODO: Update with your NVIDIA libs path
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
