creation_rules:
  # Talos machine configs
  - path_regex: talos/clusterconfig/.*\.sops$
    age: >-
      age1REPLACE_WITH_YOUR_AGE_PUBLIC_KEY

  # Any other files you want to encrypt with SOPS
  - path_regex: .*\.sops\.yaml$
    age: >-
      age1REPLACE_WITH_YOUR_AGE_PUBLIC_KEY
