creation_rules:
  # Talos machine configs
  - path_regex: talos/clusterconfig/.*\.sops$
    age: >-
      age13jd0rndp589yqxpxw36fkrn8jkgazqrlvj22txp4gfh8e0qskusq97zta9

  # Any other files you want to encrypt with SOPS
  - path_regex: .*\.sops\.yaml$
    age: >-
      age13jd0rndp589yqxpxw36fkrn8jkgazqrlvj22txp4gfh8e0qskusq97zta9
