---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vaultwarden
  namespace: vaultwarden
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Vaultwarden
    gethomepage.dev/description: Password manager
    gethomepage.dev/group: Security
    gethomepage.dev/icon: vaultwarden.png
    gethomepage.dev/pod-selector: "app=vaultwarden"
spec:
  parentRefs:
  - name: cloudflare-tunnel
    namespace: cloudflare-tunnel-system
    sectionName: https
  hostnames:
  - vaultwarden.alialjaffer.com
  rules:
  - backendRefs:
    - name: vaultwarden
      port: 80
