---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-smtp-secret
  namespace: vaultwarden
spec:
  encryptedData:
    SMTP_PASSWORD: AgBAhLgl9UZjyPEwOwjoFlXdejOz86LojQMWg95JNvCcjs+tk6SayxeBsOH2WH9zS9OqzVdu1gPrJmYGmqLhH/JJo0Pmen32PV3LPnZ61ZP5VhosnUNm7ZMh/QECmeJZil7pMm4D3js1DC88q4uYZ7WrWX9nRksXfcYCRnL7ZoXqQ3cAKrIOxr8PMI/kSoqlO7cw6GCEABsznfmUwVSKcoAjWb6ghgXw+uazfNhodNSxqhdZmYXjntWUGi646qqWJk8OrAHdSxtoeu1x8KqAqNhe1w3NvJ7lp9MOhyduPgSFMpc/e7BZ391cu6BDhPN0eUYcTuiUarzFU7/YqKtE3QnEF66N0WTKtCFV4oz+GX0AfGWDFpUH4neErgtJOtna1U8BasqZAh0IeunMYdhCydUOdMpQdNDed2SCJS4T/7b+yjM+OhNui65pI0+4U+ECo+eTLnBwayFPc3qJHTvboeVrbFomxhXLH33UU/AKc89jC8I2Q6kSESuUSchFJC3P4v0XUQCQjTSq7DcNEal2fJzSRkPY0O44xtF9KA88uqU6a1mtaCLOAYjvoBf97HCYlcxsJGFOJvpLkc1C7O0+kjkbO6L2SvHwERUciMnUZgn5Ly43CMeHr5nXBDw8yJ5v5p5BxEvOTMGDF8N20+otq24JVnkRzVzZKXDOhB2y4ILjI5hxSf2QIzontJwXU4Q4FtsKvlECFxtPmQ3JVTVPtIoM2xh5immHEBhj1IE3qZrFADfC7yiMd8a9gG+mzQ==
    SMTP_USERNAME: AgC1VviaO8XiWY/34fZ7UwYlQtYsjXJuRPdVOE74GU/QUzCQUmYcbEkpDkMQkCMr6y7kRSaEeEhcDBo5Gfzuv7Y7VmcxwhCa5kSTHmAsfq4MNxbnF/6gsVzucI3cT7hJ4X7Ovu/tzZvP4mU8gqvKh69kVUYGqO5xEQBMgLx6oBrPI+kxpU0MKoJK8xHgVN3A1s1iqfaW3eClKYn6b+saNFHOStA6uC6D6BRt2reUjCNk+83gvje19AK9CxfxR5pNvuQI4oHIqbGtJIZMJksSG4dunQVey8DnZZQCZTH7YILwbgghXoozMq6wrie8WGBwXKfugngcHfMWYypxwPSOt4muHq1PvriZzNFtj4OoECRCXZGlSp+s9/u5AuBGyuW7YbF+9lHi4oJ+2stRfnFlCUgp87TeCL+duknSgpdbdJUAs07SR/l4g5QdKlxKZ+B5Ua+heDVnEIEjmd063ADrD7XraXhyZzBmEStBsJQnWz1m38XgHyDKrb3lH7K3F21KgOoFVPqlRLEF+NNeEULPrPNkrlnvVnN4vD2rgADB+uI1STIMrrbSFjxnNOQwT3fbeIgiYw/vZVFsLTfnZJ9ktewwt70sp0ZaL1MokX5+s1UQMaRAxwhK7d5BaU8ebLqCMydCZ/mZAakyk2H/pHFivqklnpgi8YJQxqDpGYBqe9/e12OW5piW51Etjx6diYp20KtQ90C1CyBknlipOGGp4irptm9AxA==
  template:
    metadata:
      name: vaultwarden-smtp-secret
      namespace: vaultwarden
