apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - name: vaultwarden
        image: vaultwarden/server:1.37.1-alpine
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: TZ
          value: Asia/Riyadh
        - name: DOMAIN
          value: "https://vw.alialjaffer.com"
        - name: SIGNUPS_ALLOWED
          value: "false"
        - name: ENABLE_WEBSOCKET
          value: "true"
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: vaultwarden-secret
              key: ADMIN_TOKEN
        - name: SMTP_HOST
          value: "email-smtp.us-east-1.amazonaws.com"
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_SECURITY
          value: "starttls"
        - name: SMTP_FROM
          value: "homelab@alialjaffer.com"
        - name: SMTP_FROM_NAME
          value: "Vaultwarden"
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: vaultwarden-smtp-secret
              key: SMTP_USERNAME
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vaultwarden-smtp-secret
              key: SMTP_PASSWORD
        volumeMounts:
        - name: vaultwarden-data
          mountPath: /data
        readinessProbe:
          httpGet:
            path: /alive
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /alive
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: vaultwarden-data
        persistentVolumeClaim:
          claimName: vaultwarden-pvc
