---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgCeNEd6AR1jQWabnRj5yqMDxfhkuNMDTnARYqZDC9jYKg9oT7B8PcwX64pyg+IYCre34lPRUsY6rWEupesjClKQAYDgfZTg5CTZL1cD04bhzzmRN8ridCWDGK1Xh3Put2kCUBS+lCo6eh8wDkoTb89RWJy/ueWti3TBWJstK8l0NpVW3UaOWwawRvioabTJIjvckRUwCaiFMyCU0di7XTJG3K8KrDEx8/tQLS6jfpDtWWZbYAB1TRRqCs9xhinU+dWJM1Igr6Vi450ir8EGPP3qVcbA++Q31hjmy/5ANJnUwyyBlLiaUu3mXzIRs3zyXP8cT7L/stRHidSfgvl+2+vZBRWGPUYcfLrkMXysszUZnEMOMo+5xkQhInuaV/BxlX2/N2CM/Cj4mRpGb346jRX8Y2NPvw88YNcEEyNqzUNT7vmHtayVGibvgk6Ij/F3OFOUTNO+NdstDX/mvVOr0FOCFJur/aA7B4hzaurfDo4osXH0d2yVL//1DiDkGIG1sIB/8xM83zNYKzpc+MFSjt2yEhvB7qdtaTqEHd7Mibc0XXic4nzj3yeDgvBZ3jOU8nZEN3O05KxA+pLsHmB/v87Z5jv4jnbTPRXSEpyWtbO7/Y+dTyliRNu4LOrgpNOwLCRi24AvAap8a56C46sH0qmyoUpuUv2d26Oel5RGFBNCwpHIbbYxNl8M3djtDs4chiA7oqe++SqZZu2aXVKaA709uuduDV9W4eAIID+4Gqwaf5vqjh0uYITua9Fddjset1M7F5hqBMapXN20S8Jlgtbv4xk7yFXvaVVIlVyk/fZcWHdFy39qvHM0kgoYDPgT0FnO
  template:
    metadata:
      name: vaultwarden-secret
      namespace: vaultwarden
