---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgAqBAfelYwHIheWdkJwGUipUwqPg+ik/B8yFAIP5Y/btuEQkvNhYCPlJQiOc++3IZDlZu/2YFYAP00KCt+/MGC0uS6XiX1dE1dZSOVBx9RiILvdtYC2owxZeTQoy9I0guu7lne3X0uOMe1xsMTskGpTs9PpnOOenUGgqP5WeXwxDBLDzIAbbVUO/dgKjz0S5MsvrCa/lloUkmTzhC/NWhsCObwkYQSiSAAouN/5msJptBR8X0wMtVi99EREsx53vH+eGB79yWRmmIoOxOkf25k300LkvQZe0sZvelju8H3QK/leYo3w3YNRDIxluhPMbeEBSK24JZrF5p2B1tfW2GO/Q6yNnYVlN5nWeDw7ORR8XFBqR0Jf7dHKTHGqg3ykxfVdRuPjfxe3xxQFPI0XtL8MlBON4t4FwmAox/Ctol8yURVppjR7NDg2gny9w88apBFyGe2I+llorw9IswCaltJMypYNNjoQJVNpoYZIoj5sFR3fSyzeAjvdbaf+LKygj1DdIoLMvhap7tihjln7xenorypOB4qPBppHroxWECbhBd60U4Ok1C+AfPiXlnKagCP4OEJL6XSqhuUoeVjumAU2jBfnfkcPd69/kAbrsoScI5whle4txsuwUWj/Y0hxM9vkdWJ73saZwYyTg8GPlO98Gum+q2613o6sIvKXjQjMQ+F0TzebIp9nABtfJjcXdk+sGKGFlI5PPcjdIVtvDKp1SKWoJ6sHkP8IUTYFDIbQvadeBNqElJljymBwjZ4NL4DwaO+HWP81fn+l0H5KD03DzBMZ8o0MCbsWJDYGE2DudOiRCFtllWCg5Sp733TfM102OlPW/jfs8bMrBT+Sugob49r1fOka
  template:
    metadata:
      name: vaultwarden-secret
      namespace: vaultwarden
