---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: umami-db
  namespace: umami
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  storage:
    size: 5Gi
    storageClass: longhorn
  enableSuperuserAccess: false
  bootstrap:
    initdb:
      database: umami
      owner: umami
      secret:
        name: umami-postgres