---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cnpg-cluster.yaml
  - umami-deployment.yaml
  - umami-service.yaml
  - httproute-umami.yaml
  - umami-postgres.sealed.yaml
  - umami-secret.sealed.yaml
  - networkpolicy.yaml