---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: umami-postgres
  namespace: umami
spec:
  encryptedData:
    password: AgAzPCKBsbFW9G6qGkzW3Yqbc/LBPgtusiXmUG1w7e0nSyfvz6Oj9sPH1jmF5ALQU3g5ETBmn9jd8pT4psdT2/wNwBggn6k2PCzKzKCwXprDnGJGExa3HQ2nE0g78R1+fWUM980BvU5TCEyncqBWuUfreXHFLyOSu4LzhA3Nm8Jxr5o1I4QX05fxRlW8IGLLJx4GeS/K9KE9vYdooUlUfXqrronhTC6TLmBiI9jBlV19e7CuKcvMmx0IsmJY4NhGW7sLE27E4Z3/uO8Zwm4AVqDdJ21C8maAJwbH0G3m5fIkQqgHjYxe1VRUbSpMjFyfHa4VOzu9qBtM9rWmcFdY6Yqrjh3aU7jZtTsu7OUiVxJbWnztECfZJoyNMQj5Puqe7qXYDfzQV+8jZgiLrnkFh0jUbQVloJ+XRD56B6e9ObkZ5DqNEH0VCBwxQ51SrAb3zbZ97eIh6JGunrg5zFC2hyCG9l4gzPY3n3HREC+ekoiTWTmplE7xMWt6gkKYfgB8uGI+fHOfC7LH0u+hjKPfATV6JXpotOEQfnJvV5sW+bEqzIdnsbEyHAKtqO04eQUMhv7K2NrhyJRjVa99RUPNr70DrSBGC2advf+d7RDaI5khOFgTN3zyh5KlXDdiVDMAPp4zU5i0vw1devz7SuW5w3t7yVxUH3GXyLNY44iC/I8xR6yEz5zZUf2NJj7mdbLd+cAVvlM9upnWH1dHM4/uKbl0Dt8xFxV5qW452VNA9q0z
    username: AgA7VPekcett0MdF4iZw8AZoGsLmDBjiLmLnE2F/VyNSUNjieB7aL0c2lAfdiqiEJjpJlr2UpkyEyIxLoGX4XSfMXc1c4Knhuzzw2tQz/NCBhUGEhQbClBJETtVVGlsUYOmuBQkwr3LwjfOzhyf0dpEAuQcgpFGx2B7KtiF7M6nyfOXvqQrQi18GLQxiqjlBM776uIH+kQrHDbd39tdgEtn9FjX/yyMQWigScf6J7D25+/ec5QIvK2N0naN+du6eNCOVSltlmSQsYcDGPLdwxbaVtqwr4OxgjxI8IXAX1z3zz8MrnUVP4D9mfDRkrrtVsz/ouTYBFdMZtvH88tIqMTS02hiOUHh8igHmbgP92j5YHqvWtD9b7uE1UAo9+NurvR5yAVmGw2CLiiU14neb3ocXMCMwVim6xHg4pJMLY0Q+Sym498q+BxO8urXA7djtvN2p1fkyzE60Sr0MHSDQwxO7hi6dK3yMGFGrfp84O3vKaP6BZmcdzTkNjlNtT8WOMcb8inqjKms39dXhVMh/CFIJxHneq2qEWwReuidM8EQlVRVlIVUlO5wmXuHATxpD0Zo//kYzsBgXiGeuWZrGkfQGks3Ot3dIlVuy3BMQyFHltgefC43ui832rZgEUq5RndzbF+RDeoPcp1gNxwQHL4B+tG4Supl7v0Wn89bsGk7H6YfG8FutuNL1ZHzWYc8gxrq2dvgELA==
  template:
    metadata:
      name: umami-postgres
      namespace: umami
    type: Opaque
