---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: umami-secret
  namespace: umami
spec:
  encryptedData:
    APP_SECRET: AgBxcTNnkuQM0CkegWRn9T2ULC9zurk+EMBNLDuboDCN4pDoZaf9uTJK99xLeLl35s8SDg/Rr770fUxAV1CKkTzb3XIAuF31GSFBYUMGkn55+Xji4iJeikcHZEKHi3UsDW7UpQeH6iPLv0UxBbJNE7R8dLhLtvTjmXVhOtB2S4AGFx4DveP/YcC6/SJqCsBYIZJKey5ezFNl35GnWoPbQgpdUIhzOxsZ/HOaO+YWCQkSB2BCSktXimRegeudmHM3tOlUGGwb4gnHW2kFPb4O1cSD0ZM5SFofLTy6MnvdyUYx68Q85Kklz970pzZKBa5Kl5psJ8kSeCgGjHsXWcA8gvaa63owDBueEEL2dkY7TlR80fQHwsXoUR+0HQ5lTASTBMHnUh7xQyc4VUeC56OdIaSwHZPERboSooGCoadenpBf1m2KuOkhie7r0bfIKsVLp+8kH1x4r2OrroZt/8bPWjgU7X79q1CpAXSiaeseV2HFRwd7AKo7eqAz/wY1fhFMQ1aJeJ9ebGJRB/+V/XO4s/mzjPkA0Mjz/f0zTTPTA+9Zc/ykZDHYDqThCNyJ/oJqRNiVIeiwQM3cszuMe/WPnxOoG0wHAntQMaz/gu6HsmYRmdYMDRw7RJXudf3yCeItqGM8gIbKYq7tHJhB2M4nt8lT/dgihhQrN6irQ68G5kTTg7cdTVBcn8hmB7sbHbhN+7NlwokT8ti57XXoxQs+y/PhTXsED4IaoQ332AD4G7+lpS7okKxYgOxMBtfCh1GeeL841FS3GbOPn7Ax1MaDgkrV
    DATABASE_URL: AgBE3MzgpGlE3DYdcgU60uhuLZjRadf+VahRB5nQcK2K6ulSDQeRsllaT3avKYbj/jbLu1KB739YXpzScfo45O2iM3s/ZBpdsl4CfCY07svqKLAJUsUDCIVKjtWlY6qsZbDIxJDm4j/P+3zkMfbl+A/pWcueQ2QxzjcsDNG15mmU10G4VA6iGRP3zeLCq4sD79MFGL4/khF8gE1lRGP0bOV+vmZpSTEhsQE/K/nz4IMau7P6vGDqaidDUS+ktHLExzEWolyHRaEFeN7LHxJyGPtLZPhhqhba49mQ8M6l5PqI88mrNNzUyIBO4v6yDxsjEDWXvA2Efh9+fD6K8ccvEo+YDjSZtyNFcFaVHgBIvFdtp2kFg5L0IZyaHg1HrPM6KUiqMAI53x17FDvnBfXwxQfnXOnt0NBwrwvJsA21216tmyH3LwBW7GxECoKD53pEy/vy+hwCwKqOyFq4fTmIiKnJ0vrtJnl+kz7bbUVot4cTERI90OxuLaxtGvup8hCBbn22lOl6pBN48xtx5j09k+sC1MPINp5NBxZR8wt1mcFaaUtLZQANqJwfX5bPMjulW82kX1v7XLhJaBRF25t2LgcxVleiBuTagYhYTNZ9+8nX2oezOmuGbEFxFLiuTI0rZI55QxS/IrxpChhPgBfDd0+X+RJARD1JbDSmIut/y5OUCdqohoeUcKD/tZMkDzahTkUGTMUoJIhOaPgoftagBrWyrfpyHFItrAa+XTuq45LTQJ5pHAEs2fpfPVTpl5C8f1xuoJpqJUfRw8fQ6ke48z0OeTGrgGOsUIZZl89itcixwk3sd1mKOAqGIJoe0xmq48iq
  template:
    metadata:
      name: umami-secret
      namespace: umami
    type: Opaque
