---
cluster:
  mode: standalone

clientApi:
  advertisedHost: ziti-controller-client.ziti.svc
  advertisedPort: 443
  service:
    type: ClusterIP

managementApi:
  service:
    enabled: true
    type: ClusterIP

image:
  tag: "2.0.4"

persistence:
  storageClass: longhorn

prometheus:
  service:
    enabled: true

fabric:
  events:
    enabled: true
