---
apiVersion: v1
kind: Service
metadata:
  name: ziti-router-metrics
  namespace: ziti
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: ziti-router
    app.kubernetes.io/instance: ziti-router
    app.kubernetes.io/component: ziti-router
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ziti-router
  namespace: ziti
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ziti-router
      app.kubernetes.io/instance: ziti-router
      app.kubernetes.io/component: ziti-router
  endpoints:
    - port: metrics
      interval: 30s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
