apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexotv-transcoder
  namespace: stremio
  labels:
    app: nexotv-transcoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexotv-transcoder
  template:
    metadata:
      labels:
        app: nexotv-transcoder
    spec:
      containers:
      - name: transcoder
        image: docker.io/alialjaffer/nexotv-transcoder:latest
        ports:
        - containerPort: 7001
        env:
        - name: PORT
          value: "7001"
        - name: USE_HWACCEL
          value: "true"
        - name: VIDEO_CODEC
          value: "h264"
        - name: VIDEO_QUALITY
          value: "28"
        - name: AUDIO_CODEC
          value: "aac"
        - name: AUDIO_BITRATE
          value: "128k"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
            gpu.intel.com/i915: "1"
          limits:
            cpu: "2"
            memory: 2Gi
            gpu.intel.com/i915: "1"
