---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAntYQVIN/WY81SM+5+NdOuO1jqvss6tsYtgZV2klEI9TS1w3jRXoo2vihD/xiwpHzkATXLQIUHsYcVRGsfj5wOloyhF25qOWqkvVgAXy+LpckFwIG7YjCt4wzzl3+r/zMayhXXlITyyw9XYxXsBDEejQFdhVFkyflv1HedoQW/LavhUxTq+4o7jD8+VXBOn98rO/T4OfbCJfjUuDgDwtEpNB4fx+SLt+UZOm8TuIVTUr8CFSoGtdCaFpii178ske9hyLx8tfFxFukuzjrWoKxi9Ia3fIA0++oxZlFrekMeaiLW2NQDaUIsl4Js8rQmSn7/QD9DtO2lOYmsqxuGPrWSGfEMk4t296SJph3cS84DDE8VO6GGLVpJvefdnJZw/ZYzBvfKyRyB2WnJF7F3UirovuUIMFUruX/MEjEqGOjZyk63W+1nZa44zUZWc0aaXOBQfi3vOEU1MQKL6EU5PhFx7y58sGjBE6aV1xe8kNVkBAdPdmDQxOaqclLHhwEhNvHkLu2DTOScfoT3qAcm0aqHYCi4SX7+MwO/mzjD/6q91148pToMSqmUUegr0ciStRR+3nZXhs6KA89bMMaLXxgUtG7idmJS3Ua1WFIwHXYNRu3shGihadQLMHiJqJMiWmKQihgwBma3bBklx4kfORD14xDehAILWgVdO3sYJIQSpTktXQcm4+jDgwzuKFiRhXJhjFPYmdEIRgTfLSKkSwBIUvS3jdqdNi2CEDkoRjtmMjSCx6O/D/6a4iASmHIprvmYgKbSlWKqXO1W0rHco2G1adNy0O53FuAA85lmwU3K5VGCZB0ETgPZcOh0MLb4Jx1LjjUemEE67mUTQxfeYvGL
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        component: velero
      name: cloud-credentials
      namespace: velero
    type: Opaque
