---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAlv16TBzcGucYDha7JMb4QRVNjkwb1nBUD036W0Hs6rEMX5/QuSf4eLYNVrvCTLBBD7B9F8qzxO8H/RPUoQ7DglGEIuGvZIRdK54oILsE6z9sLMY84ygu0kETWKQSsX2ANRGNQmuXd76BzHatsJwV7zERoMx7kJHiUaxW9hm4zf6pgIpKGz0FLJ1CjFk5JbPo/4iKUlmyyPGE+O9+hb+7hjleUH5O/gdrV0PQRUoQoxE6NYcDk4aAFGi8gcvNmtBopED/LWCayjaa6fTxQSdI+fQRjWcuSy7iW6GouJDBwXO+xkQ92QEE1dqdq6unadaOLVMqN0XEhTjEqAvlAT8ItYN6TfdEzpf7SimxdlP5YqkHdKdFI0BY3HmocJpi0ww0z7iEcgOMV5h6x/XHIFDuSKle3AbF1g3iJzbsd71VOB2gQWLS/H8mjuPDCczHY4dH1vPhNU2uunIm6inYP4uX+Sa7n99x8QZjT21oZqSPfGx7Z1gOJs91z5Q9bMbzgpRq2LwL1VaCl+smU/Vl+HPISrZm5k1NBqZ/JCtp5n7o/oBRnsWpEHvstHbhUHW95MOc7dPDjlWTGAYete7nkdkubyqzNY3o0bJu6HgxElXKsDBZbyDxvcbBwuq9NkSRYPkJebgUrvQKJ3nKJI4+i4GosoGXuZ5/yhN9lKL3XQpa6JqaNvvhapBgsRnXMVejhvWqlVrgAeQDZMV/A2h64CYVqmhjuunRfwS4WITP0aNIJnEoOm8ER5K8jhVxQYmJoSONX3QKBFZgNik/7AHpTRy76pCd2aF5n/dTHnEpDLcM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: cloud-credentials
      namespace: velero
