---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-full
  namespace: velero
spec:
  schedule: "0 2 * * *"
  template:
    ttl: 720h0m0s
    defaultVolumesToFsBackup: true
    excludedNamespaces:
      - kube-system
      - kube-node-lease
      - kube-public
      - velero
      - longhorn-system
      - metallb-system
      - cert-manager
      - external-dns
      - arc-systems
      - arc-runners
      - kubelet-serving-cert-approver
