apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: catus-locatus
spec:
  storageClassName: "local-path"
  resources:
    requests:
      storage: 20Gi
  accessModes: ["ReadWriteOnce"]
