---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
  - repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 9.1.0
    helm:
      valueFiles:
      - $values/kubernetes/infrastructure/falco/values.yaml
  - repoURL: git@github.com:aliAljaffer/homelab.git
    targetRevision: main
    ref: values
  - repoURL: git@github.com:aliAljaffer/homelab.git
    targetRevision: main
    path: kubernetes/infrastructure/falco
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
