---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:aliAljaffer/homelab.git
    targetRevision: main
    path: kubernetes/infrastructure/intel-device-plugins
  destination:
    server: https://kubernetes.default.svc
    namespace: intel-device-plugins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
