---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:aliAljaffer/homelab.git
    targetRevision: main
    path: kubernetes/infrastructure/knative-serving
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-serving
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: webhook.serving.knative.dev
    jsonPointers:
    - /webhooks
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: validation.webhook.serving.knative.dev
    jsonPointers:
    - /webhooks
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: knative-gateway-api-admin
    jsonPointers:
    - /rules
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
