---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-prereqs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:aliAljaffer/homelab.git
    targetRevision: main
    path: kubernetes/infrastructure/longhorn-prereqs
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: false # Longhorn needs this SA, don't prune it
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
