---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
  - repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 12.1.0
    helm:
      valueFiles:
      - $values/kubernetes/infrastructure/velero/values.yaml
  - repoURL: https://github.com/aliAljaffer/homelab.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/aliAljaffer/homelab.git
    targetRevision: main
    path: kubernetes/infrastructure/velero
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
