githubConfigUrl: https://github.com/aliAljaffer/aliAljaffer.github.io

githubConfigSecret: github-token

template:
  spec:
    containers:
      - name: runner
        image: alialjaffer/arc-runner-aws:latest
