---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: arc-controller
  namespace: arc-systems
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gha-rs-controller
      app.kubernetes.io/component: controller-manager
  podMetricsEndpoints:
    - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: arc-runner-set-listener
  namespace: arc-systems
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: runner-scale-set-listener
  podMetricsEndpoints:
    - port: metrics
