---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nexotv-pvc.yaml
- nexotv-secrets.sealed.yaml
- nexotv-patches-configmap.yaml
- nexotv-deploy.yaml
- nexotv-svc.yaml
- httproute-nexotv.yaml
