apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nexotv
  name: nexotv
  namespace: stremio
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nexotv
  template:
    metadata:
      labels:
        app: nexotv
    spec:
      volumes:
      - name: nexotv-data
        persistentVolumeClaim:
          claimName: nexotv-data
      - name: nexotv-patches
        configMap:
          name: nexotv-patches
      containers:
      - image: savibrabo/nexotv:2.1.0
        name: nexotv
        env:
        - name: PORT
          value: "7000"
        - name: RELAY_URL
          value: "https://nexotv.alialjaffer.com"
        - name: CONFIG_SECRET
          valueFrom:
            secretKeyRef:
              name: nexotv-secrets
              key: CONFIG_SECRET
        - name: FAVORITES
          value: "uk: sky sports football,uk: sky sports main event,uk: sky sports premier league,uk: tnt sport 1 raw,uk: tnt sport 2 raw,uk: tnt sport 3 raw,uk: tnt sport 4 raw,uk: tnt sports 1 raw,uk: tnt sports 2 raw,uk: tnt sports 3 raw,uk: tnt sports 4 raw,uk: tnt sports 1 hevc 4k,uk: tnt sports 2 hevc 4k,uk: tnt sports 3 hevc 4k,uk: tnt sports 4 hevc 4k,uk: itv 1 4k,uk: itv 2 4k,uk: itv 3 4k,uk: itv 4 4k,uk: itv 1 hevc 4k,uk: itv 2 hevc 4k,uk: itv 3 hevc 4k,uk: itv 4 hevc 4k,8k: bein&raw,sa: bein&raw,8k: bein&4k,sa: bein&4k,8k: bein&uhd,sa: bein&uhd,-france"
        volumeMounts:
        - name: nexotv-data
          mountPath: /app/data
        - name: nexotv-patches
          mountPath: /app/packages/backend/dist/src/config/env.js
          subPath: env.js
        - name: nexotv-patches
          mountPath: /app/packages/backend/dist/src/addon/M3UEPGAddon.js
          subPath: M3UEPGAddon.js
        - name: nexotv-patches
          mountPath: /app/packages/backend/dist/src/addon/builder.js
          subPath: builder.js
        - name: nexotv-patches
          mountPath: /app/packages/backend/dist/src/routes/stremio.js
          subPath: stremio.js
        ports:
        - containerPort: 7000
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: "1"
            memory: 512Mi
