---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexotv-secrets
  namespace: stremio
spec:
  encryptedData:
    CONFIG_SECRET: AgABR1UHZcVH/3Wdy1Y+YtaZY49kSCJmFEzzAVu2pgJ2ie62DToEYiH23ea2vKMBdW05cUi98mcqtA0VgWSpvczKHPmum8+RWce6/Uz9XSDUF/PlB7HAsnDQM7sdQHsHou42/D6QL63ertZIFCLnCnxhpAtbBUOpLb+eLaAsHBS4GU/Thqu/n6WaSkGcXoiJSUR0d/DKaJJLF2f6CH3t/YhphJahRlvGL6E6AtLXYSXqXmGOLX8LAhvIs/bzdACCvoYMLWYv7rrpTczEUAz+jV47F1zQ5jwmVgMM7+dSPUqhcqnA8hKPN75rVd287E72HohqB/KwkPeGKPppB9q6YRQTgbOXG3iKjnqhz/jU98OFfigDEckAmCT3xkzPF8qLoUe0vf9H4uAQlUyGBwA4lxFZ/pyd+iTUr7e1CJ3UAvR3xHoOzw7t12vKuEtxBtJVs3eWhUC49Xb76pDyel4hYUeMWmGBxiQcZvybeXNvtH/zFEAx0TriE2HTW6aAdbNY3hutwxUdlOpteGC3SE8uzHsrgUyN6URkjzex77+S0FSOc2TBGjR8iJO+IRlkgnY2i9UWpOEqtHOp99K4F7MTBaiMhIgEBvBX1acJuqnL8wYqOh9jp0GfVARz0iQgXdgl/O1mYba23JMB5+XULKL07pMWpHvGLRLOUlu8PH9Tuh6XMItcTZ97aOkl8Yvo9R7ONgrna9RorJp/GPwUbASE2nF13GIkoKH7zvzIcpNnj1Te5Q==
  template:
    metadata:
      name: nexotv-secrets
      namespace: stremio
