apiVersion: v1
kind: Service
metadata:
  name: nexotv-relay
  namespace: stremio
  labels:
    app: nexotv-relay
spec:
  selector:
    app: nexotv-relay
  ports:
  - name: http
    port: 7001
    targetPort: 7001
