apiVersion: v1
kind: Secret
metadata:
  name: externaldns-route53-credentials
  namespace: external-dns
type: Opaque
stringData:
  account-access-key: "YOUR_AWS_ACCESS_KEY"
  secret-access-key: "YOUR_AWS_SECRET_ACCESS_KEY"
