---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frr-k8s-metrics-reader
  namespace: metallb-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frr-k8s-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: frr-k8s-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: frr-k8s-metrics-reader
subjects:
  - kind: ServiceAccount
    name: frr-k8s-metrics-reader
    namespace: metallb-system
---
apiVersion: v1
kind: Secret
metadata:
  name: frr-k8s-metrics-reader-token
  namespace: metallb-system
  annotations:
    kubernetes.io/service-account.name: frr-k8s-metrics-reader
type: kubernetes.io/service-account-token
