---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metallb-frr-k8s
  namespace: metallb-system
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frr-k8s
  podMetricsEndpoints:
    - port: metricshttps
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      authorization:
        credentials:
          name: frr-k8s-metrics-reader-token
          key: token
    - port: frrmetricshttps
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      authorization:
        credentials:
          name: frr-k8s-metrics-reader-token
          key: token
