---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-smtp-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgC2lhpkj0zTKoV6fpAzsm7gstg749PB0xkpGMlNiV4onklTQyx+KrwHpX7kXgHWJMvMT1P/gJXC9iUue3wJlpoCw8PDMyAtb8HmPsU899LBAzpsNoQ1rN3i8q8e4LW/zHwhz4VGMp0m+sytHiXAUE770rfLq3JU6VAicFnrK2HgB81qvDf0UI49FHVjHwNPJgCYviDiyWyAlQWyuYvJZPH2CBymeSCqYZQ3bxbwTC7D7X20VQLCLeD/0wIM+OmOzCUNMneaKKDXFB8qzXLIuM/zrPnH/wO8GLWCxrAI7i5xiZs8pZoXxdwceyz4bpfERzS2BV9GXbFlXobzwfBh15T7hjggQ3bXb4vvGd33mROTTOdVTlcyYWaSuThwdrX7oFFqIyc+JCixRYeerFa9SUwekdTvD0ssS77TKCuPzKtGecWiIxFC7yuPL2nzqFMpbxuquP4qph8fC8hGmnSNzFXANSVCUqjr0LUYjvJohOwyrWgngjT3ITmPSG8k08XeHYqYory8Ad+oSDBXp8BXiZKqhO4xedyDf7J/UhEYu4Mh2hAkMgqpLdHBh2fvHhSBe69QBD2+G2slKSPX7pCRSrq4Q3JGV1iHuo1CO7dLQBYyw6fwr5fSje6ikEUWKyK/OXe8Phx8372Qxz3tHRVIb4zf56EhMveoPmO/Wj/I5Z5OSyJXMK4LayK/B+omRXCxuyJBjShWd5GBvrEkrHKYJ+Suy34AFe/GHFMYknddT3AHyx8t3t08xkvR07Jl9Q==
    user: AgAZMXAZ4+xvCuOdqtF56hHHfw51sAgOQu2ZeAyzn4clIdU55QAwcCKOgK9/L+J3aULXoCKsnibfU4agsk+M+npWmsE0Ab9TXZbJWv44OYEP8M3CsI5oL14/RY9QeF9Fo5R4qkWy4dbYiWyFShQIZSYylHPY3sQLd9FCFqTQJ3EtEsd/GHTo6XELpFGvvAnNConOZh6ydvoP3QwHyqK/+UrPW2p1Xw78AkJYgqWydro4ue8YHa150zw0UW7gQ+lUwuL2ZAsqZEfURFiqqEM8LpWRJ5w3Hpep2Q2DGm1AqIdZQazxK1kO2WzTUKq0KCR6kiK9hAsVu4CMVSGLpmikuIcX5g8ort9fjD+WzqJlY/lPkB3cioVvJlutCP+jSVubC7v69Ds6lAuiZ7hcLhgbgHAgUdhcLn+riQ60+m6IwklZh0AkWCknDxfLjL6ycguYITS5DQ6WQX2+C1RatBYhziaenP1SE0X12FidgLvo+aG/oTp35YN3ZbUvsiYrlvEDErv1BOwG0TsYykrmdywRKZV2pC2Rqm8J9LqXot7+dsKUVoZ+ooG7ySuAo5xxWw8wJljkwRr7TXomM23hqB9niuxteT9fPTUcxyH1pfdB2I2wFfRhSeSGZkC1jYruYkB9oyCk2+5ybH8znLQxcB4kbJ3M95/sczMOS9DQgeYWshXd6reOfFcUdSqJVSrabI4JyqGBVsqgJhRbP6klzfLz8FrsQQnhrg==
  template:
    metadata:
      name: keycloak-smtp-secret
      namespace: keycloak
