---
connection:
  create: true
  name: default
  managementUrl: https://ziti-controller-mgmt.ziti.svc:443/edge/management/v1
  caBundle:
    configMapName: ziti-root-ca
    key: ca.crt
  auth:
    updb:
      secretName: ziti-operator-credential
  roleScope: Namespaced
  hostingRouters:
    - router1
  clusterId: default

prometheus:
  enabled: true

metrics:
  enabled: true
  secure: true
