---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Cluster infrastructure (CNI, ingress, storage, monitoring)
  sourceRepos:
    - https://github.com/aliAljaffer/homelab.git
    - https://helm.cilium.io/
    - https://charts.jetstack.io
    - https://metallb.github.io/metallb
    - https://charts.longhorn.io
    - https://kubernetes-sigs.github.io/external-dns/
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://bitnami-labs.github.io/sealed-secrets
    - https://charts.bitnami.com/bitnami
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
