---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: User workloads and applications
  sourceRepos:
  - git@github.com:aliAljaffer/homelab.git
  - https://actions.github.io/actions-runner-controller
  - oci://ghcr.io/actions/actions-runner-controller-charts
  destinations:
  - server: https://kubernetes.default.svc
    namespace: "*"
  clusterResourceWhitelist:
  - group: "*"
    kind: Namespace
  - group: "*"
    kind: ClusterRole
  - group: "*"
    kind: ClusterRoleBinding
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"
