---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: cloudflare-credentials
  namespace: cloudflare-tunnel-system
spec:
  encryptedData:
    api-token: AgAFrOVpTBw3OWElBe3VO9hwDU3kf//7K67quTVsMoO4hau2OUhhBNmXYgH785iQKrtaoHijsC59MZNGXYiJC/JsNueYHYM653pEhh2Q8S2tAzc1AE8YpUDb+Im3ypeLVfPDHaLXlvAsGASjF7AShy8xKsFJMgLqH/8gv0oamMTyyoNopqAGS199pZSpdoEy0rnXwWqMRaFJjbYj/vnktcrWXsZuFp2FzCQp6bIYe6DNQLFE4yi6wgF6hZLI5h2kPD69k1nrWqWfa80QzFKLuUiTPi0MU2B3r0RFy3Azi3T6M0BrR0V/IGvzgwz49vAiTWcoJxoUSA5C0m4/qXmWqdInVM0gcVsekfoYL/MAzibmDjmc1R5/XJ2ve1/5FKgyyp3Ji1KdZz2802idJm8DZN7kME94SdLQ6Nwe0Itxp1j0eh4b2KO0ZS7pM5F2pYq+9Tdzsk26tbJ/zNU9M5lKF6WOfWlnY0kD/fjKMzr7MYo3KtMaht23H8IOtBWzat2LJw7APKqzWNUlbXVT1TjvG/6gYaIDYpxYBE8x8vrWhgvNiUfxKoQoDjMB7MTaldST5Bvtkl/Zf0dUfAQ4GfMPYYdiMdR1plnxB8rXVL8ic7pEbV6QTn8Adah8Ma0hPVats/xk9crve16l4UyWtANs4wDnKvTyHXy9mm9SsWMq7EqnRAs0w0sRHil3REQxgHlgwg+VbjPqMeZdqGFQAdutuWR/F5UBuQXDYrM0hr8vl9NIb23hB1yj1uZPCTx5Wmjudk4sM96LWA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: cloudflare-credentials
      namespace: cloudflare-tunnel-system
