---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: cloudflare-credentials
  namespace: cloudflare-tunnel-system
spec:
  encryptedData:
    api-token: AgCH9zdLDFA8gd8Cs5oOftwjVoy6oroMcDcWbS9vkZ9bDqhFx6GYiIPKOyfryo9DVNeyCIDNY76vgQq4Yb6DFrJEWxab12fh2WAR6ryrJC7606yNHDOkrmiYGZ6gDS6ebamfzTfFvuA+1U5xV43YQUI7RYu/d4nTlk1f3NPFqUHP5DTTByEfr/+Xubi1VFWmGqW52yiuCJ9VOqiVUEwpqc17w8ALgaxfdDGUlFqq/1eEq5wr2Wfk6mdT8Hj9kn3HNgj2ZHbc1+LtrGxNUn98r2bD7rfURvEnsMZeoPzCoBIhfXgoiZb8P5oO1bZfVd4rprmA9EvXQHesgbmvjbTPURRV82e410sEiwmixOASWRWs97fns1m/hqytlZsa9ouOytl25D2x2jgkCQoDhpHgFmj7H5pj4I3bqwpVuHIL0eEbB/bmeFMy9tiJY3uRNOVsOmOdvwTOdGTC6QxGGgz6rJEhUCzMcz5eixsLxUzKtP5Y0H/A+pYVFkkQzqHEuxtzhsLGdDxk3zXz83o2JuwW+BPmEP12OHvJtawLA2O2aRPMpTfyHINNZErh4hrZyDpq/zmw+5NvimjzeJChe5oz5j1ntLQ6Qe/jDEbGw5zbi8VsHq/xAi8CJJ4hB4oXlIBqERBBOBfQ5VZg2sFPpfT0Fkjl2tinnR9xNYicjPvSbVBD6I7lrC2EYtQe+EVXdOHLAmrLXpVj4X/vXPSFjkh1uQRcDVkU2Lxv7y6osYvpKWbhdANtbLp/SLVPVbYe4pZ2RhOFWYKb7A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: cloudflare-credentials
      namespace: cloudflare-tunnel-system
