---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: cloudflare-credentials
  namespace: cloudflare-tunnel-system
spec:
  encryptedData:
    api-token: AgBY/8qwPhKW0bWMyuxAG+Vckq6stHyMCmV0TQ8cj1NaqnU6bIfKzgzQkDjCPF6oQpzNM4KZjsEI6k05wWUI7fcu1gdngyOa7Ei2X5lFOTTdohMa2RUBlOOmH5KXKuQgFaA2phKfGijNKDezV9nuw+GVlSFDhvHv6XCTInTNvn4qZDBqhoMgfLN3rl1TRCKCAxVd3Q8acz9MFHlcGy7AV5qfqusqH4g5F8NFq4HuMxKk1e6+Rv4F3mCX3FgTQXJn87AcMCSQ4FG/u2NEWvL/FR0paJ752aJOHeuOtH7deCU+Lgn7Ah1rHK5JU3Q6iU1Ve1EHQNaJsjSaRarsbjkiL5rMmYgnqS0eFbiqdCNbb3RoqiScUKRYAeAl7WWhL4qk7gBozsZ8CEw/jUH/OFVnkpojuXY7rYI4j8X5FfieOLyBDdj01Y1CQ1oLMYf32OBcZJNiChgkITOBX4tT7c86hp9wSjJbccBmy/V28I9ymDYKkh1eRJPaLCqWTs7qX3RLTTGUsdy7+sW7Ke5g/ezIkV91sy2rEraLvF9as53z/wY9nJqvwEq5QVtnFjG7ZhbNJdgS8IyQaZ1qG961ExeLQL75amlr7hF9ZmU5tKCxPpzFsWwTQunBKCRYQhFERTHwmWKBaNSIwXHfzdb7N7dH42bhPHmlyqMYB64ePNicSLq7IZV9/GVUeu7lc/Pd912p5A9qzFVVnfL5fBWXlCi1Rx/mJoF+kcT5Tcm+qxpES7flLPYkvqma+Jz5LcL0KsXbEU9Wqtvf2Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: cloudflare-credentials
      namespace: cloudflare-tunnel-system
