---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: ArgoCD
    gethomepage.dev/description: GitOps continuous delivery
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: argo-cd.png
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=argocd-server"
spec:
  parentRefs:
  - name: cloudflare-tunnel
    namespace: cloudflare-tunnel-system
    sectionName: https
  hostnames:
  - argocd.alialjaffer.com
  rules:
  - backendRefs:
    - name: argocd-server
      namespace: argocd
      port: 80
