version: v1alpha1
debug: false
persist: true
machine:
    type: worker
    token: ENC[AES256_GCM,data:uhttbjYlNoYUfVQI1eEPqEGjGTAEoNc=,iv:p1jFnekkhZTVL+k681c8dgDcGyZ3y35FEJdn2RUYMAs=,tag:B6F6bVbqaeGOEa6w6REOhw==,type:str]
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEJJLzhPcVIyWGpZWDZZOWJXZzFCMmJNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5qQTNNamd4TlRFd01ERmFGdzB6TmpBM01qVXhOVEV3TURGYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBUFlKMW1hc2RtdlpLQzFwUmg5Z3pFMkJaMjUwalo0RGgvcE11ClcrS0NCbHVqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVSHZQOFpYQjBjWWtPKzlvOAorLzZFSUx1RkV5Y3dCUVlESzJWd0EwRUFESE5TWHJ5MW9LWVpNTFc0VWNKV3RtenlhMEs4ZUxKNDVBbG9LakdxCkYzaTVYWmhWS0ZOTlUvaUN0TnZQdWdJL3pXYkIyVlo0bUsyaUloYlEvanZoREE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: ""
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.36.2
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    install:
        disk: /dev/nvme0n1
        image: ghcr.io/siderolabs/installer:v1.13.7
        wipe: false
        grubUseUKICmdline: true
    features:
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
cluster:
    id: hPEZEXUQ2jkxmyO6ueDejoY9OkCLFGOFjqLpas6WNug=
    secret: ENC[AES256_GCM,data:f29IYXfGy9RTlWvdiG4pd5JFFvSwhxbT3f+sTpqmBny9UHDrCgf9Fbz8hUs=,iv:Ml9wR5Zw8aXdpFhQXqfhz7e/I3QCNDMbskLhHIvfK0c=,tag:AO6X1XG/rhdl95QF8+qOMw==,type:str]
    controlPlane:
        endpoint: https://192.168.8.99:6443
    clusterName: k8s-homelab
    network:
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: ENC[AES256_GCM,data:ekTp/9ZXWdiDk9vbMGbALNvqSTianIg=,iv:2oLltEFPM5xSrb9tFtiifOpadZ4REYQWTOcrc5ZBHtQ=,tag:tiNvUkqkGsumgTFIpG3bMA==,type:str]
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpekNDQVRDZ0F3SUJBZ0lSQUpvOXhydHpaemVrQ3FTNVAray9ZR1V3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakEzTWpneE5URXdNREZhRncwek5qQTNNalV4TlRFdwpNREZhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVJMNUltUjNnTzNnN2ZyQWJKb2pkRmJmckZPTUIwYitTK3QwbjBxazh4ZTI3NDk0SXY5bXZqVGFQb28KTUxHclVKcFlWTStiQmEyQTRnY1Z6bFpHVWNmR28yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGR3lrOVQ4U1M1YURZWFFWM2VDSEFCNmtXdlRTTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDMVBTQ1IKL0pzK0RZbS9sZjNOM2NISGNWRTZZYVh1bisrWldrVjd3d2JUVFFJaEFMZkRWb29vaUp0VjUwb0NWaUxtSUhQVwpMUmNnVnlOUkdBNUE5V0g5KzZFdgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: ""
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUVBkZzZlaS9GUzBZMWxI
            TTRMRVVSTDZmMDlFQ2JYUnZzbGV5a2FiNW5FCmRkSWZBMElDb0FrdGxONTZoTWc4
            YTRLaFFDMTBpS1ZkSWt0OE0wMlR3NE0KLS0tIENvSkl6dFhFYXVudGtQU2NjREhM
            T1JqWlVETnpPS2x2dDk3OGdNZXd5V00KCZK4iqrSB8qDNdDFG8EqLBoYlTI11cDB
            FUNTQMZwMLSt/dDhaxqbua65neBDO0aumAGkMV5DWKHsGsHnScl36w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13jd0rndp589yqxpxw36fkrn8jkgazqrlvj22txp4gfh8e0qskusq97zta9
    encrypted_regex: ^(key|token|secret|secretboxEncryptionSecret)$
    lastmodified: "2026-08-08T16:23:50Z"
    mac: ENC[AES256_GCM,data:Of0Yvh+oPSlmm/JvgdtYX4spNPN/cgNH0ShrJwFccSriHyhI8wzDd8whXTcctgLg6fibBTnF3mi+ejfXv2BIRdYJJKFS+8NNG0zTuIuoqSOJiU3LplRLuz77Jrq+jTjkRVTdlcd1XywPnyvtkxNuEKY3jHdLaMPz4b7fI3MZdmQ=,iv:b4xdM4b/SFeMJ7orlblDtIk43Q1KuE+zWbiVO1oAQQU=,tag:9aP64qT+4dv/Bu4Ffkn5Tg==,type:str]
    version: 3.13.3
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: wrk3
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUVBkZzZlaS9GUzBZMWxI
            TTRMRVVSTDZmMDlFQ2JYUnZzbGV5a2FiNW5FCmRkSWZBMElDb0FrdGxONTZoTWc4
            YTRLaFFDMTBpS1ZkSWt0OE0wMlR3NE0KLS0tIENvSkl6dFhFYXVudGtQU2NjREhM
            T1JqWlVETnpPS2x2dDk3OGdNZXd5V00KCZK4iqrSB8qDNdDFG8EqLBoYlTI11cDB
            FUNTQMZwMLSt/dDhaxqbua65neBDO0aumAGkMV5DWKHsGsHnScl36w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13jd0rndp589yqxpxw36fkrn8jkgazqrlvj22txp4gfh8e0qskusq97zta9
    encrypted_regex: ^(key|token|secret|secretboxEncryptionSecret)$
    lastmodified: "2026-08-08T16:23:50Z"
    mac: ENC[AES256_GCM,data:Of0Yvh+oPSlmm/JvgdtYX4spNPN/cgNH0ShrJwFccSriHyhI8wzDd8whXTcctgLg6fibBTnF3mi+ejfXv2BIRdYJJKFS+8NNG0zTuIuoqSOJiU3LplRLuz77Jrq+jTjkRVTdlcd1XywPnyvtkxNuEKY3jHdLaMPz4b7fI3MZdmQ=,iv:b4xdM4b/SFeMJ7orlblDtIk43Q1KuE+zWbiVO1oAQQU=,tag:9aP64qT+4dv/Bu4Ffkn5Tg==,type:str]
    version: 3.13.3
