---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catus-locatus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: workloads
  source:
    repoURL: https://github.com/aliAljaffer/homelab.git
    targetRevision: main
    path: kubernetes/apps/catus-locatus
  destination:
    server: https://kubernetes.default.svc
    namespace: catus-locatus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
