---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - couchdb-pvc.yaml
  - couchdb-statefulset.yaml
  - couchdb-svc.yaml
  # Uncomment after sealing:
  # - couchdb-secret.sealed.yaml
