---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-discord-webhook
  namespace: monitoring
spec:
  encryptedData:
    DISCORD_WEBHOOK_URL: AgAFn0Fkl8bMInOwUgmELceOR7+Y9+0qoOAf2lBMfn/rDVF7htn4omaF0znMD1ZuGVVCHuJW6VBh6D3vrjpndUOBIq3vcs1iuouRdtS97Xv/wcZ3sainjuUm0LlyXQ33OGdgfSwpxeBlKA0aOBjmnR3GFiRkp3+vse5Cbwt/jhNV5QuQml+JEt8tDShHugaKn2WkTPvmjtiQoNrDFr+aXe11ju/rAyTHCy8jff1eGzyBvZq5bKPKdsPr3jd8DtRxlq3ejUjFzOl5F85rAXFCs1I6l9tqrxPFMDjzmpe3OST5zcnVtbKrEswb4em6WUnGrHBno4VV8ZfgMtb3Ec8EwYimS9siBFpUcDxedMr72sWBgKZ5z560xfDyPqD5YgA9xIvTgFdruHtrOInIrW5S+dqbzUk6P6qkrL7JNT7KvOipwzFaOExAYJb0gJuKFOXU905a+bogXUNQB/L86qbI7svpUb3Tyc1eFFCX8CDz2apJaomYXc5VOCrktEmlwuWd/VzLdWGOIkdEVrR6FXmBGfqOp0NHejgILhWVm9J6isgKeHYPk1PtTeQZlXFy59f7X/WVPyZq7GMQdL1+lcjlrDZcbcCjZ+hV4FZZXT7gtF3nVfRa3JtVO9WyTb5+IFKBa/CYpUJpB488Z4lkwiMrfo9ZMapQBaImI1/jyWfUeOApAf4JU+bVqVZt49OxSvXf4+QFF7C73Kg229fCEkPkMC+ScpA98e6e44HqbFBNGgqndKGbiNud6lX5jOBz9RZZ5jlfC7Eup9Vb93+2Z8T4hbL9mpSPigQmxNBzKS7xy2BvUmbofJIxkqLcIcY4mJ/+4sHQaKbfx87g9TvvfadQ6erHDvamUqOGiKti
  template:
    metadata:
      name: grafana-discord-webhook
      namespace: monitoring
