---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCoKr3VKY/UWE5lp+adcSXvO2ItvS4G1MckxNdk/egCrMkt840XJJ5orLhmdKMhQEtxswWs5jO8LwQU1wB8Ot1Fda0t0D2mOBXa/D6+FqFIOyRCvCcXikVIOWqWbumDti/UtmYdaeIgYWAvhwgopOhdcGlk6Vpz8BSZVjuqthao+mGP/LTWaW6FolqaI/FAo4atESAU5+UhH9Sdz9vtyEieiqiHWimCZWSfocc2bJ0LDbw+THpinRrBge91KSeR9qMkK6z2eyvYgHXeadWuO7dsw7KdUFB2+iHfYGe9XgiggGHtdHgn6QQjDvC6XoujA1EQtvIbD0YSvKLUFl1sWZy5pYPYCSNDVePAjpjYEm1JjU8wRBbj5j8aDpBoNkj6iH9/ccr3wl892ka9efFKSa08JshGJmR9s4bW91j/swEu/JQgoZ7PV2ECKpMUFwwyd8ZkQ5VwPklJxKzKPdVESBxE103I9qn2RJ/nkSQRfbilDVOUPMUkvEGUIFffgSdIsREQd7DV7VOX8rVIlW5CQoWUcTNPBAm0Zzx7qEJXER4J0BUEg/39YwrPl+9DbmjUmKvjwkbKAtTwV+1FJsaP86g5zV9BFfk1wsoERHS29v2voAcdhFcMP8yJhoqXx/t1X41tpv5gGmw+z2jH5nB1Bkr/MjHDQOjiz47LkoMIFGqm668p4RuzWjtlhNVrnn+zAxwwfB8fry8vyFpMeTxfX5hCEzjeIBF5ipIqHDSuqTjvAw==
    admin-user: AgCqWJipkjJK8FQtiGN1xsFXjIS0QMCLHwQ/OAsd+S9MO8k9MAFt4aD6/Fby9QlCX9phFLFstHpjrm+QHbGDg01IpeVzoHJWqXLKxio257gEEBotlE7pPLB2wgEZxpUy7gIKmArtjlUf2U5Z3yYWtsQO4di3887/8/c7ch3k7atopOHgGrGdxjrm0CvS71Y8UholqR895jaWtQPIlSAYSVgRGXL/j05L06u8peSXR87hWvt0iDC4Rd6duzkA6cInUqNENBlpWXAKhizHn7gl62wDbXfjGhF3kVOwgPkf7+KJgOINdysbDby0wJ/5vAaqh1gCkKzgm4GTZYGzoXaD/JsSpyUQkOWP2nxCaashTqffK5MqoMlWIYpyUCjMOrXUy9udNOcSm6grKxL9gxkCCEFGmPoVeU6Tfm78Yj4Hj7a6Lk8BMhCwu2ZCJKS/D3RJcDJedyW3FckGLJQ5v8Wzcf3ztfX3zqhyjznR6ZRd+y8/hroTVv2QWXDBzOgPUHrBzKsvADz7zzcEl6PiqzAT62bbuwDb/YmIW+7mwFg/d0dK2S5J2Hbnwo4aXwxtBLytqJLw1eZGsT85uNT1S600Xd6KesMbNurZORHOL76DbXNGYDwtYb8+DYAAEr/AhlOiU8PE8YyTt8FR/gSHxlcVW9QR28VS+EIHqrNbgEOkREFBrDyeehWep1kakjev4dqxMmto9LfQfQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
