---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-github-token
  namespace: monitoring
spec:
  encryptedData:
    GITHUB_TOKEN: AgBrgAzdFPiZDD7LfEgH4T+fzYM+v5GqHR+8zCD1ehiG3eAkUvqX9pROFut6QNJFKwyLwJ175IkeYraKfvrl1WqxN53glh+qm/zGXHrEzQOQYB7ITegNHeZ3a8V50L1DYn1kiF5yHmBmPCdZEjuq460om/2+PcAM6Q2KDkTQGmPb1Or0L+zzG3oHjOoqtoJnl2NJzjSLCqJs6yvyidwh68d6Sx/Y+u+0iJZ49h8rc1CQ7FWDTUQGeyYjeTJOJr+Zni50VZOQ3OEIR9btkeuThM70upuOiHfqYQQl0sG1zdDbOFOJVzzJKlU6yzeG/lL5GcnTCJy56BvtuduE2Yap1JJz8AZFUfXZ0CxWuBVbslVh79Ur7vCMxKjlgF9Cxuf8SIRlgll04iG1jkSgRdwu5o5fDe5CJEqwAQlyrfLzdA0qfgnqARrlBSf14qaewDtM9jUBBsv1/+42L/N9qPxm6++bkA9wk7IOcQ9/bW4/gvqph8Wy6saJG0xsVdYBrxEuLSylcZ+JqIAV2fifTnOuGITKq3aG2CDH31otQc9amKiCVRmk72t9RVZkQ5eJnIpwbac7IdEFHDpxL+Rf5s21utdT1/W9bkWNu5LpNDuTtjeRg0fzlLk4in4IHLsTAVO5ZYXntpiEkeAnfyfO9E2lXKCFOKb5W9jak0Zjxz8xZVqOb0EZg63CFxJI28G4uJ+esArGvlwzBgDM6a4J1gLV3Xv3vDlhAV1D8nh7mhv7TZUO5pHBfGzgYSGV
  template:
    metadata:
      name: grafana-github-token
      namespace: monitoring
