---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-github-token
  namespace: monitoring
spec:
  encryptedData:
    GITHUB_TOKEN: AgCzfiDLzC7ulf2mhB7wAO6+TvfAiiIozlro2NT95HI+dXEyTSvkNeiAtJqHIzAys+1B9i0YSgGyT5C8/UTCiea79tKJgiaSy+oWgUdeE6iyFRZzE5RdcEVhK08CQwDzspCfxLivtN+B0e0KJmQFKzNSJ5O4oVXzgTGYcdrvpM+3bjozxUaexA61R7/xHuerGbLDZvbAWA2DjAnrk5t/DDKV27MTjskMgitOQAohR4WCBBuKDRaBzqunuTItMSzqIMTnguK+zD/3AfDaoukTHLXcmN6HhuD6A1dC+ucuIXHtPWRATsPN5SLKppMoBj81U9AFsTbhB553ogpzLD6QZAt+WOAY+SuU7qN/W0d80nzf/p6E6jshJ/Lmc2czXsL0gVdBwVEL4LqHQsFVyzvFVYs7aFrkEHtCz5qldFbN0c8NBRpr4Vy9oj9wa51l4EQmIznO/6563jc6dgHvlPE0DnSCiAAxFXOexCtEKs8745CxDpHm87NMo7gMvkk9GRlc7lBLfzlnF0YHAxUXlbssx21QYLE9P78+9LTn85DLTBOWzNe79o5eucfsGHQIseRjzW36Kv0dydWzfT4aSfk+VxLPS8HJw/lAZ+4M3NJgeitdQQRGY3vaU1eE3omDz/62j5BPTYLxKXTHnr3xD+ZkS3iuktRfbdRL6rJjfS30Lna413fzYUINWtGgRgA650vCN0gQsuHnXymDjGJnjelzQM8ve7RzK/aCguJbCDOGj+GExvbGwPc4E1cqdTwZCjjJN+DEtSvvlgwshWNpTY9r9X1dVrTh6HFmLM2rlKzWMb6qu3NaD2eLnPNRxZHG4Qs=
  template:
    metadata:
      name: grafana-github-token
      namespace: monitoring
