---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-smtp-secret
  namespace: monitoring
spec:
  encryptedData:
    password: AgCeaw0dYqxONpYFr+CwfXQhU8Rr/U/ZvJFD6SrhGR1Goy3WljqZ5YGXbGeXd0f+uzN8eYRJ9vuvZ6cdNFSRM2t7lTpR22dPUzJXaUuIL2p9EcYJc/OKslCLyJFetRWpy50N0tZGnMl1fNRCe1kI8yIwe+bRN6cgTcI5gMbaUlOkAboqsJ3i2DErbQIeYOIG5PltHPNt3lHh5YV96JdljlCL7UtqNjUelJWCOAZRZvH6TBWIjyzWkTpPYUGGmSfQE4VrsipO6pa3qFXlqnJM/6dzcRS8TFEtHBENcGqLTlkumSvPzMG50KHSdyZW4m1OeZqApizC/6zeeR/cYCc+qwKN9Ob/wWKxtM5Qpc7HJV9VvDZ+ryowKwT7uPO93R39t8MzpOA1I5biJeDR7C/+7vS/hCKs9ll9nJAqzUwvGRGbbBSAvtXx9TUcZBl6nWX3wgXMG1Mg5pj27fihPCj7JB5oLNmnnTQjH0DJ5sEIMG5SFz1LjbDzLd36CNrP0WfCsLncCJFaii9Sb+LOHKzYbAwyNedqeM5rPD0X7qgmGFyQci7kYZ/5O3zgoBhK+XOfVNAp6OiB8fxdjoLQ+3hM00AtP1TEv2D7Wvvq864MIURuZSK3Af4QP9g/rduAVNPFa8S0Ywoe1lbrQ1aJ/C1DvNPq65L+/MEaTXupmzNVy8jTftJ8obtBzS9g4x77oAHJ7pmFAhvbbVx7ENeb2wUu0NHVj5b2/rfCneSdKkN19yZ5xcOWn0XuzNgQoLRtsA==
    user: AgBxbalXSbZUVb9KEIfogDkxBkcGSjGxiuMZy8Dg3Rk50kIu8GPgKx7D2WaWYW/bCx0i8O7+dqIwuyVLISHZyewzKPpRJ1fLJqNzlwHKZpQ4YxJ2qK0+YenIoxKRlF0fbTYSk8w9cSN3J11wbX+uKkcXcs6CnRidc58aCOOkaqBf+QWLrY1mCN/xcvlW3VUt/h1cCxZ9F9r36kmebvYGNSEvwOpQyBnKuBcph8L2NH+DUctEQBOK36KVVcfIFeo3sBjN8Ms0Ach7Z5/k2w3lmTeCLfURo4rE2p+Dqu7EWYxhJa/cuq3epmj/GOpy5G/DuMMUbeKejzvED4pwy9DB0m7o8Bznou0RjnmYHhKbknO92DZzxPPD5L/p3zsbqHTmYbcj+dXGiEXFg2f/nUA0uSbYr0g0bz5nCDkg59nDMAW9O66e4ez6LUnazxckJrAW3AfmnXnKed9sNXS2zxNkb+ASzvLDmsuYt3nyxKARDgHtb/LQ4ZUQ/HvTrP+4Rx1lPiI1yCDrJF2gvEvlLkikYns/H+VskD9ULqHfhMig/h/EdrDtphC3XibbbTCAcqDRAa/vhAUFuD9XIFWV6X7LpEdVEs16trpWD8TQfxnBYNty4lEDlF2SPqADtA5KQcg8t0K62LWuBO7MslkTloNxaVE/Lc94XV6C4b6NTkP8IsqT0tZfUNvXfd1C+FCICIP9HVfAmYpqMeKZes5lZdm+rTXNfbuifg==
  template:
    metadata:
      name: grafana-smtp-secret
      namespace: monitoring
