---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - httproute-grafana.yaml
  - thanos-objstore.sealed.yaml
  - grafana-dashboard-argocd.yaml
  - grafana-github-token.sealed.yaml
  - grafana-dashboard-github.yaml
  - grafana-admin-credentials.sealed.yaml
  - grafana-smtp-secret.sealed.yaml
