---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: fffe45f4-79d4-4538-a9d6-ae4ed2af455d
    credentials-file: /etc/cloudflared/creds/credentials.json

    metrics: 0.0.0.0:2000
    no-autoupdate: true

    ingress:
      - hostname: team4.tuwaiqtracker.com
        path: ^/api(/.*)?$
        service: http://catus-locatus-svc.catus-locatus.svc.cluster.local:4001

      - hostname: minio.tuwaiqtracker.com
        service: http://minio-svc.catus-locatus.svc.cluster.local:9000

      - hostname: team4.tuwaiqtracker.com
        service: http://cl-fe-svc.catus-locatus.svc.cluster.local:80

      - service: http_status:404
