---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: cloudflare-tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgASo3He+vaMH4XPY+pev3VzOQEmozRtuF8YpiQQF2jqWc6CrRMSU0RpbJApC/2ylpANoFjGJSmJqjBwY+9ueYT1K470nulRW9NcGjE97Yf6inUQ83jZl6/MF9c7nNoCIjM6TERiHpnTxw45imL9Sysn54mO9+QixMnR+7v5jPVorID/Wb9hictKI8BmThTNXZS9ZFbQMHVAwn/ILYBpRT2G0M1m74JJowP1SF9FPqdQtB5saSlKWzG7VOpc+gLQ8rnIdXFiY07vDbM7+quZL4EeJwyqXxwWpS/Ri2PQQq+O+WIaDqiNJ1SnugQYSV2AaCGTFl1fDKKZiBIkxw6dBhag/XcklLzBm1mZUCTjeg81Q+kmgWXhxWT5V1XdxHhCxShAspE8PyeAWs0NulJE4AjNEz9qO+TUxIr5WD1EmVDcrTxwbcq1RxDyw/Ac00k0rK6u+L8NjyW0wi/sB5AjY8GUbzQsvodrvmMMTyW3cFLNs4pr+IG3+Pw7MIb2VKm0On4qVQBWP5sME0svYTqP2rZmInm88KbT8Xywpb8L0IHxhXtEf5mkg5N0qeG6C1/4qwjLtC6p/i8DbtVGWjnoCbszhMxIOA7pya1K25pKehD0OFEhyC3rH5shl296UIYiYPZ5KOkFfVO3FVmDYvCukfXoCxFZiQmHAR98TPKiJ95iT4hYbKNqurwGsuIEnEfMT9AzTVHKb1Ey5GRPUCFvMC6fez8B2Xm/ilYaEB6FZurSuf29JaDqiGB9A5oZMPgGu9bq5EdDihzqiYPP4bsnLOLXvC1ei1+hdHfDv7AsseAg3akkqY6KuA+LubR6dFyvChujAVp9kF5tTX4iv0dEwUT5epeQN7gz8FVPcRKJ+wAB5EJb5qymBQNsTmiqI3KlYM1+TN0/Mp3h8tU0p0GUv0I/zJK9Lqj5v82eWWVD8aRt
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: cloudflare-tunnel-credentials
      namespace: cloudflared
    type: Opaque
