---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgresql-cnpg-cluster.yaml
  - minio-cm.yaml
  - minio-pvc.yaml
  - minio-statefulset.yaml
  - minio-svc.yaml
  - backend-deployment.yaml
  - cip-backend.yaml
  - hpa-backend.yaml
  - deploy-frontend.yaml
  - cip-frontend.yaml
  - hpa-frontend.yaml
  - httproutes.yaml
  - secrets.sealed.yaml
  - minio-secret.sealed.yaml
  - cloudflared/tunnel-credentials.sealed.yaml
  - networkpolicy.yaml
