---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: minio-secret
  namespace: catus-locatus
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCImm5B22N6aPBrSrha+vTrq2SDJ7RG6KNGqtmow6juHGL3euo629iAa1nBMJSF56jbSokyRZPbAq4GEsRuxbvT7CZZtSlpi1jqccy1PWaH0vGnfVO/VlRbGTQDOQL9hwEffEzRVLLRfgUyVuREs//BYPt0rHOeElch9D/GlAa8jg8QmXbBkIrAgrxSd8vFMH4IckwrBPo5tmNSUMTj/TeDOZosxodUs0QHP77iZ3rpj3V1AZqJ4a5b34l2IhEt6hlZoHMRYjhnRJU5MNG72lzEbbT6eB/AQVzebjWFQ8u78BexV/bm1ZEnMBxFVCnx24O7AIemlmqePhlwQb0zJtAToHzQPNngdDwpeQtLXESue/JoJzJecsHZ/DEvNghvQSJOfFE9TsSw9ZSLgNvoALaRJo+AqMQaqt9oojncc6Z+bt9OkZD4AEkugpJLR6Pl4+0caaq58411tNOR8UYRHTMLbTpQu+nWPx2wwvhl4V8CtnG2W37WqT0LIbg4xI//kzC2Y3Kr0CZywaVQqmMIXpb62oxeCctqdV5VBku3hCp8rzkC72i+/kkmR8M7EpHVXad1oKAhseSV6cPCGRIfFWmHLb1ChF8+byCCmFb4qv4urPv989kMUhyRWMZ+EntpG3hddApXpQ6uLhgAYeLj0PAJnqeKjgwVKpHvCb/qSjTBvot8kyrz+WorXDEhWUGgl3gmtTkIRG1ru/q1hgTqL8sm
    MINIO_ROOT_USER: AgC3TWhxTEirVwHGr5NWkmdsNRPlrcd8snHKhEd34y6taGzlcJD1J6FVBs9v3wjeUrZDJeYXKOuljwGVbTsLCFwWk7yE0J4w5AP+7B+xlpW84pzjJhicXwCVNRWy/iP08fnCbW4hqru+PTxDY5CwxFhRjNOnOr9oTX2LPkodINAE/bT15cr/0uZZoPUhOfjHN/2QV/iB9Hggmj7i5PgMUqvbPrEUTpJc+yGpXYnH4k8maDa2GVBb1Ms5CjccPCZiZOF+w3Li1poJR6tFxHwS4Ls0FfECrWnq+RSM4gq7fThSoFUHNXnsZDPJfONE7jDdIafdUP6dXOlGkaBHctmjcWFZDzYAuF4Vjb50gMXhqcVrJBgcUqc9JtB9cpWjBUHbDAVlT2U4cJMKvWa7v3CfFOVT5jRIP4tUkX4GZ412yK/0ND98YIqO6f9bAgS11JHB6RC0lvvN38fz33+9w2dMaoCh7pGDxLO+6uFjZ7PqnM+euhISjYcxJH27zNjrTjIucOEM3DNq40G1DfhQp23QW+Yf6l1nNsZpSfIY4eM8qYgwBu4zAcu3zW7iVyjPKAMdvHdKhrkY+Ouu8GSn19kj30gTI16ZylrGBNMos1tZL7xwCSclB6eUi/AKi/OrEzKVeyN7Bdo1ZqmcXOMxA/B6I3vTB+1yd6uElYNA5JgcIObAwkQkBe1NXXWW/xQIvZJJ2hiOgRk/qQm6vBv+1Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: minio-secret
      namespace: catus-locatus
    type: Opaque
