---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: catus-locatus-db
  namespace: catus-locatus
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgis:17-3.5-9
  storage:
    size: 20Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: catus_locatus
      owner: catus_locatus_user
