---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: route53-credentials
  namespace: cert-manager
spec:
  encryptedData:
    account-access-key: AgC0s4vj/dU5rkmxiy1mud0+z/AW3vd/Fy6J76O5nqK6AiWk+Yn96779VUXqEgePwufjTCSKRyPQ46CkyAS+QbCcZMnfutI9bI55nqSc46NbsFg9ZNBXArPVArad3sN3zLHP9hjHUkl5lP10vfJfogL6IO2areh4vxxDyG5FgS6vljOltpeMTwD9+3lxCWOhQsjtZx0hRTGyHLWyxdCKyPMyuUm30wfRRjgUyrEdoMoF8d1rY9U5NPikMjlRn3RFTr8rnteWw7I7JILmbded9bTmR5yJAR/brjTZUBTCa65TE+8SW1fppKzVL51FKE8CRlRe3x0/nhY799qBfjcSqKPAGt7C8REfkZo1dXiH5mI+pRHGRKnpBQEKQo7PNeWVBrNVoPA4DmvAonYZkJqku/56QE/157RqS/O7Or4p5pXr3V7DqUAbowsZAJOoUOk+K+I1B+WkunFHUjzHZswFVB2Bo2qt5V4YIjxKS5kQK3ATZQv44kVt1PeYr5/+TIyBFTGAYjYaZ6oKM79bksVBVFXFCP77RUILHKKmAXDOWHN0GZxAxVDAmMw32HpkyxKtEZGbmGeY78VkrO3M6N0g7x1CBE1Z3G76Rz3Nn9D/we3RGEm61Gy/1YsmtbIDxdDpegmbOA2k9ZRZalhavgUCfbi6kYFIbrjWCsNSgNkGmha/2/qoPi57R7hBoXiqZksQtYejglfCnWNElf9RaQ0H+S6h/phLzA==
    secret-access-key: AgB1zyvhzOd5t4stueeprFzfCXc9x72h6KJrdHnpdaqT93MbpjoczJPFiW7xVjXoJGHO9diiZ9hRPaej1LyWwfWYvkpYSLCopzF9CiUAupIrCzoFnY4Fdp+IryIft1vgfDfloyV2MO3zqx2O5xSxrG6DDoXD0FSQMafxLpJXOIs5IYsD9DUHWI31OnoXAhhv5H4z+YW+6SrKfey8ZNLmkDwjQ9ISv2yC1VWV603ItHy1wXOG/xMa3thdG15Aa2viBxFbtM6ntXtLUFgsuUpJWt5FxSwsdXHfb1gEQZGpMzqjkCSuRzRaKB5Fwl8nMoW+eFHFCnWI3573eaUr2OL4H4eFPalwckIPj3QOblmzD+JEwtET3D+PGixXXFSg5VdbOOhe3wsJmlI/m5NbzAhhL2/+CeCRb+94VgU9C+73OOeqkqY3MHPouu1iDlQMDnY6C9aHvnYpw2NlTBORtTB07kjhzcojaD8xU4APuSeBMTbQp98b8gYxJxaRsu1ZgmKdQUuTZpimiJfH11S8Ns6dCIJDB97qQeue3mTgHk26xpRivwCP1MBGQoAqpk7A0meNO2amK3bOYxYepPzpu/Q9Gm5+U6eNamMBzztB6yV56ynbtW5i2nBdrgYXScqmsbDOGXo3qPf87mIEdJg3WWoU6shaZfsGMuF2f7PzvVC0+0JT0ciFw2Tzfoahqr/G6TNwZwsm6HvhnpZQ/lvq51M/twUU1wWo36oU2ZxvohM9mMzBSXd11/vgC/RX
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: route53-credentials
      namespace: cert-manager
    type: Opaque
