---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: externaldns-route53-credentials
  namespace: external-dns
spec:
  encryptedData:
    account-access-key: AgBDRcPV+0lQHHnd0UquqEodYL2zGLyZKXbmIUILXNFFmdA3zPlvFk2uNgY/ILREPs0EKiDFF6U/5qBOYl+9ydm3YwMqUIGQk6tFmZNchyvXzvvJC9W3MalKtufMIR5ii4FexiwPEvnR4L7ksbWuschV6JWd9WWEMPzKsH/0Tgniq1axxZcAR/+xBkvx4YMzOPtfGh0YOV7uTCyySnm9AcaisqvDb7E4dSz2vV7Q8EruiR3+AGYOzxFjHbEh3aQUkXkYG9lL+ta23iYdSPaL9RYWjXgYWF4qDKzAdIGcf7T7/6vgFsXp0zWunYBDawtQtx8M4XEBkTvq4kMPiqtiSbBXqAW8qe6OzJuXpi+nb0VN6gVfmZxzEGu0U6YTUH5vFOLjL/zrQHfksXEAvKT/EifXoPLP1RYn4GM3E9LOIZQaMfc/enoSZrXHe8kOeuni36ETQ3r2Va7/nsKdHUdFeErGaKb/LGPOzu6kG1QPtkzk4MUw53PoropVmQcTx/d7lPoIUrjjY8jgWvJvawOg+B+ac78IcC8zlnrEVg19Nn052uZTmeK6YPxEHP2Kv9EzKywp85+ONh/jZ4zSgd19E66inTmfF37ShWYfF0cJSsDK/GR82+TR7d/Yq+CuontJ0o7sS5JxXTwlQ4/oSEJdgPQpMh5A7ULk+ZpVSfdWWVVf9raJJjhjJKwIUQ4zpAB9wPa5IFTZPWDJyXtRIPymQHYq7zyf6w==
    secret-access-key: AgAZRomFta7htkK/zXiuui6rB4InTh45H5VfmkSTT79cDQtVxwfa8tsS1Tz/8VZpJBkvcaPuqrp2AyxFA8jt+pS7H6eXxtenWhy3S09XTtMAiwW9hPtJGt64wp7su65AtBVciy18ZYSejgVaS1wjjEPAdI9qdJ5NSdt+mX10tDaNhWWq8qDnNeaigFmBK32PrPblUmGQ8TdS5bNaVTorWek+/AvYkvMP8dlZ0VeGS4QF1dhcQXDEalPNnn7lTi10cQp8a/Xb7UH4uGoqUgKcFccXhefjOZz4iRSjadv0x4llmHIu31dskgcO7i7utn8K/XI71AJviqiBthyVyJK0MdvpehjGLslEsUHe3+cMAUNNOFbU8rVd+4D5pd5EkqEtZzKLzRW7RPTgB/sX+KSwmcNRU693x+D1uDBMJ/XYKLfzYpN3jrAwgot541Uv7LA4D/17/fmPX23DXlIV6/W/RmrevRhFaiFg+2MdGOjkMT9nFjDzCBzDWzDt1XOC9s7DRmA6zqWnnXD1KgsBWXizp2CIGInzu1RnXspnpF1i/4Pi3/FpRDkLX+FmcZd5I1/gQ2NwYgN79sTMzk9rFs5lCZaTAVL9FCkoc+hWRk2cALmRU7rCe1cQdExDj4bMM80+cUgdR/lc2YXrFbc/gfLHdR+EUg+uqf9ok4TX6XtPUlN0FuRwiAmIcdTvSguySYHozdGVCQLRLgY8HnjElkus66viuCF3CRxebpts304wZBYbGBDel2VZGYLT
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: externaldns-route53-credentials
      namespace: external-dns
    type: Opaque
