provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-token
        key: api-key

txtOwnerId: "homelab-talos"

policy: sync

sources:
  - service
  - gateway-httproute

domainFilters:
  - alialjaffer.com

serviceMonitor:
  enabled: true
  additionalLabels:
    release: monitoring

resources:
  requests:
    cpu: 5m
    memory: 144Mi
  limits:
    cpu: 20m
    memory: 288Mi
