---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: cloudflare-tunnel-credentials
  namespace: catus-locatus
spec:
  encryptedData:
    credentials.json: AgCEqE07DIBiVKDlkgZkVA3zQZHLAe80TxlomdMKc554hdSxuG6g68UWwGhKI8bX2wGOUUha/y9h2EVgxvDlscOnRAQtCoZO+SgqD6p5yJup8C6DnWsDJNG0E8BMpFGZAuG3/iIamWhgrUPwbpY+304jDskU2kNYTRUyKArMNcMv/hsPo8dZzgeSiGfO+BliV/7cG3w4eeF9gz6NgMHbpfiqhWuXqXQ3V3oY2QdtMLy4qIlmeWV0e+VVfjOxQSVVSTmAb2FNa+k8s0Wkq9MtxbCTrQ6s4xS7sYlL/ndA735K/TDOW+3b8agvzTqqMiK6O9ZUvLpEO1WLcTPP368jxlN/tmTnEk1F3rauJbKZDKeSg7Be1dYwvm49DN1tsdHNzxYGrLh9e/SKSJafCfTF5dNZcJ4Z9NytnxKgBSHzZCkMh9RF6JhWZZIUi+95+m4fHW607iQyyKAowE+n4VcDjdcad32IfZMReZW4OM4MPaKiOO5zv47rq2awwLy3bTteOSDemL3epxf0tl4j4v6v9IBULDl4TgsYaYJE7ZHY8f+3qfDSKgfDrjfLdpiELCMMef1rpEnHbyD9ynBLDwRux+CRX+Vn9B1dOAW4j+P8ACctvW9MJKG+vSKCu9ZL6XXFeLJUg7r/hrNg9/MGbqtMl2mVOnFrgY4y34lWcBN+Ex5IVycAu/Qkt1EJNYs8kbprT8VqTw9mirvfFKkhuswei1T/hYzOvKXfqYKjIjtmO0wwP84Kmn9lenXip/CIuwX+/xykdQScwhBTaeA3poJTH9WjkeEY4VaPg+4W0ysaPRzDqjOn/+NlkIeOzTy7uRKrdaMkHiZgSoTln9mel+n9fOi+xVcY9U9IObMgK9ex1hkbXOn4M7G6VLXRqXn9icQw8i8gLtVsHZMrvKPNMC2WTD43wMsodxWhFvf3iCpXNYz3
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: cloudflare-tunnel-credentials
      namespace: catus-locatus
    type: Opaque
