---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vault
  namespace: vault
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Vault
    gethomepage.dev/description: Secrets management
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: vault.png
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=vault"
spec:
  parentRefs:
  - name: cloudflare-tunnel
    namespace: cloudflare-tunnel-system
    sectionName: https
  hostnames:
  - vault.alialjaffer.com
  rules:
  - backendRefs:
    - name: vault
      port: 8200
