---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vault-aws-credentials
  namespace: vault
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAb2wlK1OasKn6c0qWrXLN3IkLpKbG28vXeMb/spvX+n4hUNvZLMAuFSyU03zOQM9PjxVgyQzOtd1e9PQnPOL0qKgucNjdSjaKhEb3G5P8qb5f70sOIc6Z5937y9Y7bvNRWnE9yiXK9J/FxnjZAdnPuQCK9qtVKVa2pQqfOVa1lEf5LgwqhSX7+jkbwxoLEEnU47NSiV2jmW6l2TgRiber4VTp9E68e1+dyFA48xnyE9NLuf3WgfNbJGdo+ySnJqY6oWlyFO0Nc9rahL6UgEJLxGXBxC24EzqfMP/U4Lu0jRnJbDm4WvCB97iZQ9/l4g3WNfjj9rm1f3Qso7OrIeorJysIFULYfjfIUhNgJmlg+kxl41cbtGtBiP2p1Fz8/jnldA695G3reYvKzEZ4VojjN9saJj5QekBkHjw/2RDnhDL8FQfDUfAKDkN10SsBVNHH8HiF1iOnZO7dT2JOZ6vRnXXTPyzIcHuS2CvZ7sTu6pP+M6fqUhSbKrPM2NCAHfYn732iZ2ml6Om0PqbqQ4pNolgrtzCSmnNKb1Wy3n6DML8fj16OI/NoEo/6radYxH3xUotOlec/Y99SYJf8JhSiE1XNHxaJY8Yb7mLfhvgJJJzejSUxdQGbJP8oGxdXoasDXts0QOVKdXlNpumVuzRHMh0iomDkM+mHm4iW4nme0ZP1dfquGP2w5MqhRgWfH8v0uGPTqAjY8oAdeLYJYSnOQWBC4vw==
    AWS_SECRET_ACCESS_KEY: AgB7ONsPOqb+LXJt5ZVAAhY8LSUB2owVAjgcJcRdpe/eG2LLAcfJV7YW6Cbn+aZ7f7htW1rNuMC8t8hUYQQHTE7t0Ab+j8FQn5AxKatRGI6Nvob6k1WRO3WxBDi6+7AC0FKpCRfU+axdHh/nNibHpceOsF5cKNav7X3crF6Qb80qCn68XtmWaPExRe1IMGHgl1XdTrFJVEmf5kIbV/NzIwjySoel87leOWk/TID7+zizM17qd4J7IpyphECcMNlikt8PO+WC0pTV3Xbu5nnN9iEEJqwNEDtcDohwYlL8JjtVK4bmnMbfok6HzNJdMOXYOKqGMMNA7LB9JqohRqByPzpdyjYZvZZkOHd+E9RUJKvx7pNYxjXdVoyzQAhRKXwaS3GeXNloP6BaG3AAQ3Z/EIPqC1pCMYKopHJhKRG0y8fgfCOLqBVMOwz3XXl63Vy0P7KZTkfV9XF8Lh5AKhjwQLqPFMMx7/tg7usHAItAZe/3Te0LvFenQyrxhlSIT/VW05X5gJ8p7/cU5f7/WhIeNiKJnMYWQ1bjOCb8cVq2SbTBYg1ZLWFmMOJKuAVxEg/3QQzJ5HKugE7+s/SpZunfrtGJCTMNTN7HlCfyGdaV6dZOCxJeLHqDEwXLJeuHHwg+WOrbGWsj2TV6l1wWtnX835Kx516ifvdtRYqjPyrWtU2A5srU5jF7HB0YUlT0aAUMX0e9ZA9oyd5nlGGt3VIWrfgYhJ2u+NQkWhWG6n0MFYrMiVv7xsZGSv/5
  template:
    metadata:
      name: vault-aws-credentials
      namespace: vault
