---
admissionController:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: monitoring

backgroundController:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: monitoring

cleanupController:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: monitoring

reportsController:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: monitoring

