apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio-svc
  name: minio-svc
  namespace: catus-locatus
spec:
  ports:
    - name: 9000-9000
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
  type: ClusterIP
status:
  loadBalancer: {}
