apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: catus-locatus
spec:
  storageClassName: "local-path"
  resources:
    requests:
      storage: 10Gi
  accessModes: ["ReadWriteOnce"]
